server:
  port: 8080

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.54.248:3306/myblog?useSSL=true&charset=utf8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-wait: 50000
      test-while-idle: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static
  servlet:
    multipart:
      max-file-size: 10MB

#mybatis配置
mybatis:
  type-aliases-package: com.*.mapper
  mapper-locations: classpath:mapping/*Mapping.xml

#显示sql语句
logging:
  level:
    com:
      blog:
        mapper: debug

pic_folder: /home/yanchao/person_files
pic_save_path: /home/yanchao/person_files