server:
  port: 80

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/interview
    url: jdbc:mysql://cdb-kw4y0d0r.gz.tencentcdb.com:10022/myblog
#    username: root
#    password: 1234
#    password: passwordfordb1$
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static

#mybatis配置
mybatis:
  type-aliases-package: com.*.mapper
  mapper-locations: classpath:mapping/*.xml

#显示sql语句
logging:
  level:
    com:
      blog:
        mapper: debug